apiVersion: v1
kind: Secret
metadata:
  name: cluster-vcluster-example-product
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  name: vcluster-example-product
  server: https://vcluster-example-product.product-example.svc.cluster.local
  config: |
    {
      "bearerToken":"<argocd-token>",
      "tlsClientConfig":{
        "insecure":false,
        "caData":"<vcluster-ca-b64>"
      }
    }
