apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-nginx
resources:
  - namespace.yaml
helmCharts:
  - name: nginx
    repo: https://charts.bitnami.com/bitnami
    version: 18.2.3
    releaseName: app-nginx
    namespace: app-nginx
    valuesFile: values.generated.yaml
