apiVersion: platform.example.io/v1alpha1
kind: VClusterRelease
metadata:
  name: vcluster-stable
spec:
  channel: stable
  chart:
    repo: https://charts.loft.sh
    name: vcluster
    version: 0.29.0
  values:
    controlPlane:
      service:
        type: ClusterIP
    sync:
      toHost:
        ingresses:
          enabled: true
        services:
          enabled: true
